/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContentWrapper: typeof import('./src/components/ContentWrapper.vue')['default']
    LinkItem: typeof import('./src/components/LinkItem.vue')['default']
    LinksWrapper: typeof import('./src/components/LinksWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
